- name: Create dev user
  hosts: remote
  become: true
  tasks:
    - name: Adaugam userul daca nu exista
      user:
        name: dev
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Verificam daca grupul docker exista
      command: grep docker /etc/group
      register: docker_group
      ignore_errors: true

    - name: Afisam statusul comenzii
      debug: 
        var: docker_group.rc
 
    - name: Afisam stdout-ul comenzii
      debug:
        var: docker_group.stdout

    - name: Adaugam userul la docker grup
      user:
        name: dev
        groups: docker
        append: yes
      when: docker_group.rc == 0 
