apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: alpine-pod
    tier: utility
  annotations:
    note: "Custom command + probes; no external dependencies"
spec:
  restartPolicy: Always
  volumes:
    - name: work
      emptyDir: {}
  containers:
    - name: alpine
      image: alpine
      imagePullPolicy: IfNotPresent
      workingDir: /work
      command: ["/bin/sh","-c"]
      args:
        - |
          while true; do
            echo "HELLO: $(date)" >> /work/heartbeat.log;
            sleep "${SLEEP_SECONDS}";
          done
      env:
        - name: SLEEP_SECONDS
          value: "5"
      volumeMounts:
        - name: work
          mountPath: /work
      readinessProbe:
        exec:
          command: ["/bin/sh","-c","grep HELLO /work/heartbeat.log"]
      livenessProbe:
        exec:
          command: ["/bin/sh","-c","grep HELLO /work/heartbeat.log"]
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 2
        failureThreshold: 3
      resources:
        requests:
          cpu: "20m" 
          memory: "32Mi"
        limits:   
          cpu: "100m"
          memory: "64Mi"