apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: backend
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend-app
  name: backend-app
  namespace: backend
spec:
  containers:
  - image: nginx
    name: backend-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
