apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-pod
  name: busybox-pod
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: c1
  - command:
    - sleep
    - "1200"
    image: busybox
    name: c2

