apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-pod
  name: my-pod
spec:
  containers:
  - command:
    - sleep
    - "234"
    image: busybox
    name: c1
  - command:
    - sleep
    - "234"
    image: busybox
    name: c2
