apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-env
  name: pod-env
spec:
  containers:
  - command:
    - sh
    - -c
    - echo "$USER_NAME are parola $USER_PASS"
    env:
    - name: USER_NAME
      value: root
    - name: USER_PASS
      value: parola123
    image: busybox
    name: pod-env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
