pipeline {
    agent { label 'docker && pip' }

    environment {
        DOCKERHUB_CREDENTIALS_ID = 'dockerhub-creds-id'
        DOCKERHUB_CREDENTIALS = credentials("${DOCKERHUB_CREDENTIALS_ID}")
        IMAGE_NAME = "${DOCKERHUB_CREDENTIALS_USR}/python-simple-server:latest"
        CONTAINER_NAME = "python-server"
        PORT = "8090"
        WORKDIR = "${env.WORKSPACE}/jenkins/exercitii/ex15/"
    }

    stages {

        stage('Echo Step') {
            steps {
              dir("${WORKDIR}") {
                  sh 'printenv'
                  sh 'pwd'
                  sh 'echo Deploy to Kubernetes'
              }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh """
                    # Delete previous deployment if exists
                    minikube kubectl -- delete deployment \${CONTAINER_NAME} || true

                    # Create deployment
                    minikube kubectl -- create deployment \${CONTAINER_NAME} --image=\${IMAGE_NAME}

                    # Expose the pod on port 8090
                    minikube kubectl -- expose deployment \${CONTAINER_NAME} --type=NodePort --port=\${PORT} --target-port=\${PORT}

                    # Get the service info
                    minikube kubectl -- get svc \${CONTAINER_NAME}
                    """
                }
            }
        }
    }

    post {
        always {
            echo "Deployment script completed"
        }
    }
}
