pipeline {

    // agent { label 'docker && pip' }
    agent any

    environment {
        TAG = "${BUILD_NUMBER}"
        DOCKERHUB_CREDENTIALS_ID = 'dockerhub-creds-id'
        DOCKERHUB_CREDENTIALS = credentials("${DOCKERHUB_CREDENTIALS_ID}")
        IMAGE_NAME = "${DOCKERHUB_CREDENTIALS_USR}/python-simple-server"
        WORKDIR = "${env.WORKSPACE}/jenkins/exercitii/ex11/"
    }

    stages {

        stage('Test Docker') {
            steps {
                sh 'id'
                sh 'docker ps -a'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir("${WORKDIR}") {
                        dockerImage = docker.build("${IMAGE_NAME}:${TAG}")
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKERHUB_CREDENTIALS_ID}") {
                        dockerImage.push()
                        // Push latest tag too (optional)
                        dockerImage.push('latest')
                    }
                }
            }

            post {
                success {
                    echo 'Push-ul a fost efectuat cu succes!'
                    echo "Vezi imaginea aici: https://hub.docker.com/repository/docker/${IMAGE_NAME}"
                }
                failure {
                    echo 'Push-ul a eșuat! Verifica logurile.'
                }
            }
        }

        
    }
}

