# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#ansible-collections-ansible-builtin-file-module

- name: Creează un fișier gol
  hosts: remote
  tasks:
    - name: Creez fișierul /tmp/test.txt
      file:
        path: /tmp/test.txt
        state: touch
        mode: u=rw,g=rw,o=r

