- name: Uninstall NGINX
  hosts: remote
  become: true
  tasks:
    - name: Stop nginx service
      service: 
        name: nginx
        state: stopped
        enabled: no

    - name: Sterge nginx package
      apt:
        name: nginx
        state: absent

    - name: Remove nginx config pentru toate librariile ce incep cu nginx
      apt:
        name: nginx*
        state: absent
        purge: yes

    - name: Sterge toate dependintele ce nu mai sunt folosite
      apt:
        autoremove: yes

- name: Instalez NGINX
  hosts: remote
  become: true
  tasks:
    - name: Actualizez lista de pachete
      apt:
        update_cache: yes
        cache_valid_time: 3600
        
    - name: Instalez nginx
      apt:
        name: nginx
        state: latest

    - name: Ensure nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

